let table = [
{
"atomicNumber": 1,
"symbol": "H",
"name": "Hydrogen",
"atomicMass": "1.00794(4)",
"electronegativity": 2.2,
"standardState": "gas",
"groupBlock": "nonmetal",
},
{
"atomicNumber": 2,
"symbol": "He",
"name": "Helium",
"atomicMass": "4.002602(2)",
"electronegativity": "",
"standardState": "gas",
"groupBlock": "noble gas",
},
{
"atomicNumber": 3,
"symbol": "Li",
"name": "Lithium",
"atomicMass": "6.941(2)",
"electronegativity": 0.98,
"standardState": "solid",
"groupBlock": "alkali metal",
},
{
"atomicNumber": 4,
"symbol": "Be",
"name": "Beryllium",
"atomicMass": "9.012182(3)",
"electronegativity": 1.57,
"standardState": "solid",
"groupBlock": "alkaline earth metal",
},
{
"atomicNumber": 5,
"symbol": "B",
"name": "Boron",
"atomicMass": "10.811(7)",
"electronegativity": 2.04,
"standardState": "solid",
"groupBlock": "metalloid",
},
{
"atomicNumber": 6,
"symbol": "C",
"name": "Carbon",
"atomicMass": "12.0107(8)",
"electronegativity": 2.55,
"standardState": "solid",
"groupBlock": "nonmetal",
},
{
"atomicNumber": 7,
"symbol": "N",
"name": "Nitrogen",
"atomicMass": "14.0067(2)",
"electronegativity": 3.04,
"standardState": "gas",
"groupBlock": "nonmetal",
},
{
"atomicNumber": 8,
"symbol": "O",
"name": "Oxygen",
"atomicMass": "15.9994(3)",
"electronegativity": 3.44,
"standardState": "gas",
"groupBlock": "nonmetal",
},
{
"atomicNumber": 9,
"symbol": "F",
"name": "Fluorine",
"atomicMass": "18.9984032(5)",
"electronegativity": 3.98,
"standardState": "gas",
"groupBlock": "halogen",
},
{
"atomicNumber": 10,
"symbol": "Ne",
"name": "Neon",
"atomicMass": "20.1797(6)",
"electronegativity": "",
"standardState": "gas",
"groupBlock": "noble gas",
},
{
"atomicNumber": 11,
"symbol": "Na",
"name": "Sodium",
"atomicMass": "22.98976928(2)",
"electronegativity": 0.93,
"standardState": "solid",
"groupBlock": "alkali metal",
},
{
"atomicNumber": 12,
"symbol": "Mg",
"name": "Magnesium",
"atomicMass": "24.3050(6)",
"electronegativity": 1.31,
"standardState": "solid",
"groupBlock": "alkaline earth metal",
},
{
"atomicNumber": 13,
"symbol": "Al",
"name": "Aluminum",
"atomicMass": "26.9815386(8)",
"electronegativity": 1.61,
"standardState": "solid",
"groupBlock": "metal",
},
{
"atomicNumber": 14,
"symbol": "Si",
"name": "Silicon",
"atomicMass": "28.0855(3)",
"electronegativity": 1.9,
"standardState": "solid",
"groupBlock": "metalloid",
},
{
"atomicNumber": 15,
"symbol": "P",
"name": "Phosphorus",
"atomicMass": "30.973762(2)",
"electronegativity": 2.19,
"standardState": "solid",
"groupBlock": "nonmetal",
},
{
"atomicNumber": 16,
"symbol": "S",
"name": "Sulfur",
"atomicMass": "32.065(5)",
"electronegativity": 2.58,
"standardState": "solid",
"groupBlock": "nonmetal",
},
{
"atomicNumber": 17,
"symbol": "Cl",
"name": "Chlorine",
"atomicMass": "35.453(2)",
"electronegativity": 3.16,
"standardState": "gas",
"groupBlock": "halogen",
},
{
"atomicNumber": 18,
"symbol": "Ar",
"name": "Argon",
"atomicMass": "39.948(1)",
"electronegativity": "",
"standardState": "gas",
"groupBlock": "noble gas",
},
{
"atomicNumber": 19,
"symbol": "K",
"name": "Potassium",
"atomicMass": "39.0983(1)",
"electronegativity": 0.82,
"standardState": "solid",
"groupBlock": "alkali metal",
},
{
"atomicNumber": 20,
"symbol": "Ca",
"name": "Calcium",
"atomicMass": "40.078(4)",
"electronegativity": 1,
"standardState": "solid",
"groupBlock": "alkaline earth metal",
},
{
"atomicNumber": 21,
"symbol": "Sc",
"name": "Scandium",
"atomicMass": "44.955912(6)",
"electronegativity": 1.36,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 22,
"symbol": "Ti",
"name": "Titanium",
"atomicMass": "47.867(1)",
"electronegativity": 1.54,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 23,
"symbol": "V",
"name": "Vanadium",
"atomicMass": "50.9415(1)",
"electronegativity": 1.63,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 24,
"symbol": "Cr",
"name": "Chromium",
"atomicMass": "51.9961(6)",
"electronegativity": 1.66,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 25,
"symbol": "Mn",
"name": "Manganese",
"atomicMass": "54.938045(5)",
"electronegativity": 1.55,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 26,
"symbol": "Fe",
"name": "Iron",
"atomicMass": "55.845(2)",
"electronegativity": 1.83,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 27,
"symbol": "Co",
"name": "Cobalt",
"atomicMass": "58.933195(5)",
"electronegativity": 1.88,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 28,
"symbol": "Ni",
"name": "Nickel",
"atomicMass": "58.6934(4)",
"electronegativity": 1.91,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 29,
"symbol": "Cu",
"name": "Copper",
"atomicMass": "63.546(3)",
"electronegativity": 1.9,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 30,
"symbol": "Zn",
"name": "Zinc",
"atomicMass": "65.38(2)",
"electronegativity": 1.65,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 31,
"symbol": "Ga",
"name": "Gallium",
"atomicMass": "69.723(1)",
"electronegativity": 1.81,
"standardState": "solid",
"groupBlock": "metal",
},
{
"atomicNumber": 32,
"symbol": "Ge",
"name": "Germanium",
"atomicMass": "72.64(1)",
"electronegativity": 2.01,
"standardState": "solid",
"groupBlock": "metalloid",
},
{
"atomicNumber": 33,
"symbol": "As",
"name": "Arsenic",
"atomicMass": "74.92160(2)",
"electronegativity": 2.18,
"standardState": "solid",
"groupBlock": "metalloid",
},
{
"atomicNumber": 34,
"symbol": "Se",
"name": "Selenium",
"atomicMass": "78.96(3)",
"electronegativity": 2.55,
"standardState": "solid",
"groupBlock": "nonmetal",
},
{
"atomicNumber": 35,
"symbol": "Br",
"name": "Bromine",
"atomicMass": "79.904(1)",
"electronegativity": 2.96,
"standardState": "liquid",
"groupBlock": "halogen",
},
{
"atomicNumber": 36,
"symbol": "Kr",
"name": "Krypton",
"atomicMass": "83.798(2)",
"electronegativity": "",
"standardState": "gas",
"groupBlock": "noble gas",
},
{
"atomicNumber": 37,
"symbol": "Rb",
"name": "Rubidium",
"atomicMass": "85.4678(3)",
"electronegativity": 0.82,
"standardState": "solid",
"groupBlock": "alkali metal",
},
{
"atomicNumber": 38,
"symbol": "Sr",
"name": "Strontium",
"atomicMass": "87.62(1)",
"electronegativity": 0.95,
"standardState": "solid",
"groupBlock": "alkaline earth metal",
},
{
"atomicNumber": 39,
"symbol": "Y",
"name": "Yttrium",
"atomicMass": "88.90585(2)",
"electronegativity": 1.22,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 40,
"symbol": "Zr",
"name": "Zirconium",
"atomicMass": "91.224(2)",
"electronegativity": 1.33,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 41,
"symbol": "Nb",
"name": "Niobium",
"atomicMass": "92.90638(2)",
"electronegativity": 1.6,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 42,
"symbol": "Mo",
"name": "Molybdenum",
"atomicMass": "95.96(2)",
"electronegativity": 2.16,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 43,
"symbol": "Tc",
"name": "Technetium",
"atomicMass": 98,
"electronegativity": 1.9,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 44,
"symbol": "Ru",
"name": "Ruthenium",
"atomicMass": "101.07(2)",
"electronegativity": 2.2,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 45,
"symbol": "Rh",
"name": "Rhodium",
"atomicMass": "102.90550(2)",
"electronegativity": 2.28,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 46,
"symbol": "Pd",
"name": "Palladium",
"atomicMass": "106.42(1)",
"electronegativity": 2.2,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 47,
"symbol": "Ag",
"name": "Silver",
"atomicMass": "107.8682(2)",
"electronegativity": 1.93,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 48,
"symbol": "Cd",
"name": "Cadmium",
"atomicMass": "112.411(8)",
"electronegativity": 1.69,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 49,
"symbol": "In",
"name": "Indium",
"atomicMass": "114.818(3)",
"electronegativity": 1.78,
"standardState": "solid",
"groupBlock": "metal",
},
{
"atomicNumber": 50,
"symbol": "Sn",
"name": "Tin",
"atomicMass": "118.710(7)",
"electronegativity": 1.96,
"standardState": "solid",
"groupBlock": "metal",
},
{
"atomicNumber": 51,
"symbol": "Sb",
"name": "Antimony",
"atomicMass": "121.760(1)",
"electronegativity": 2.05,
"standardState": "solid",
"groupBlock": "metalloid",
},
{
"atomicNumber": 52,
"symbol": "Te",
"name": "Tellurium",
"atomicMass": "127.60(3)",
"electronegativity": 2.1,
"standardState": "solid",
"groupBlock": "metalloid",
},
{
"atomicNumber": 53,
"symbol": "I",
"name": "Iodine",
"atomicMass": "126.90447(3)",
"electronegativity": 2.66,
"standardState": "solid",
"groupBlock": "halogen",
},
{
"atomicNumber": 54,
"symbol": "Xe",
"name": "Xenon",
"atomicMass": "131.293(6)",
"electronegativity": "",
"standardState": "gas",
"groupBlock": "noble gas",
},
{
"atomicNumber": 55,
"symbol": "Cs",
"name": "Cesium",
"atomicMass": "132.9054519(2)",
"electronegativity": 0.79,
"standardState": "solid",
"groupBlock": "alkali metal",
},
{
"atomicNumber": 56,
"symbol": "Ba",
"name": "Barium",
"atomicMass": "137.327(7)",
"electronegativity": 0.89,
"standardState": "solid",
"groupBlock": "alkaline earth metal",
},
{
"atomicNumber": 57,
"symbol": "La",
"name": "Lanthanum",
"atomicMass": "138.90547(7)",
"electronegativity": 1.1,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 58,
"symbol": "Ce",
"name": "Cerium",
"atomicMass": "140.116(1)",
"electronegativity": 1.12,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 59,
"symbol": "Pr",
"name": "Praseodymium",
"atomicMass": "140.90765(2)",
"electronegativity": 1.13,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 60,
"symbol": "Nd",
"name": "Neodymium",
"atomicMass": "144.242(3)",
"electronegativity": 1.14,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 61,
"symbol": "Pm",
"name": "Promethium",
"atomicMass": 145,
"electronegativity": 1.13,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 62,
"symbol": "Sm",
"name": "Samarium",
"atomicMass": "150.36(2)",
"electronegativity": 1.17,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 63,
"symbol": "Eu",
"name": "Europium",
"atomicMass": "151.964(1)",
"electronegativity": 1.2,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 64,
"symbol": "Gd",
"name": "Gadolinium",
"atomicMass": "157.25(3)",
"electronegativity": 1.2,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 65,
"symbol": "Tb",
"name": "Terbium",
"atomicMass": "158.92535(2)",
"electronegativity": 1.2,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 66,
"symbol": "Dy",
"name": "Dysprosium",
"atomicMass": "162.500(1)",
"electronegativity": 1.22,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 67,
"symbol": "Ho",
"name": "Holmium",
"atomicMass": "164.93032(2)",
"electronegativity": 1.23,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 68,
"symbol": "Er",
"name": "Erbium",
"atomicMass": "167.259(3)",
"electronegativity": 1.24,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 69,
"symbol": "Tm",
"name": "Thulium",
"atomicMass": "168.93421(2)",
"electronegativity": 1.25,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 70,
"symbol": "Yb",
"name": "Ytterbium",
"atomicMass": "173.054(5)",
"electronegativity": 1.1,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 71,
"symbol": "Lu",
"name": "Lutetium",
"atomicMass": "174.9668(1)",
"electronegativity": 1.27,
"standardState": "solid",
"groupBlock": "lanthanoid",
},
{
"atomicNumber": 72,
"symbol": "Hf",
"name": "Hafnium",
"atomicMass": "178.49(2)",
"electronegativity": 1.3,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 73,
"symbol": "Ta",
"name": "Tantalum",
"atomicMass": "180.94788(2)",
"electronegativity": 1.5,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 74,
"symbol": "W",
"name": "Tungsten",
"atomicMass": "183.84(1)",
"electronegativity": 2.36,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 75,
"symbol": "Re",
"name": "Rhenium",
"atomicMass": "186.207(1)",
"electronegativity": 1.9,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 76,
"symbol": "Os",
"name": "Osmium",
"atomicMass": "190.23(3)",
"electronegativity": 2.2,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 77,
"symbol": "Ir",
"name": "Iridium",
"atomicMass": "192.217(3)",
"electronegativity": 2.2,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 78,
"symbol": "Pt",
"name": "Platinum",
"atomicMass": "195.084(9)",
"electronegativity": 2.28,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 79,
"symbol": "Au",
"name": "Gold",
"atomicMass": "196.966569(4)",
"electronegativity": 2.54,
"standardState": "solid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 80,
"symbol": "Hg",
"name": "Mercury",
"atomicMass": "200.59(2)",
"electronegativity": 2,
"standardState": "liquid",
"groupBlock": "transition metal",
},
{
"atomicNumber": 81,
"symbol": "Tl",
"name": "Thallium",
"atomicMass": "204.3833(2)",
"electronegativity": 2.04,
"standardState": "solid",
"groupBlock": "metal",
},
{
"atomicNumber": 82,
"symbol": "Pb",
"name": "Lead",
"atomicMass": "207.2(1)",
"electronegativity": 2.33,
"standardState": "solid",
"groupBlock": "metal",
},
{
"atomicNumber": 83,
"symbol": "Bi",
"name": "Bismuth",
"atomicMass": "208.98040(1)",
"electronegativity": 2.02,
"standardState": "solid",
"groupBlock": "metal",
},
{
"atomicNumber": 84,
"symbol": "Po",
"name": "Polonium",
"atomicMass": 209,
"electronegativity": 2,
"standardState": "solid",
"groupBlock": "metalloid",
},
{
"atomicNumber": 85,
"symbol": "At",
"name": "Astatine",
"atomicMass": 210,
"electronegativity": 2.2,
"standardState": "solid",
"groupBlock": "halogen",
},
{
"atomicNumber": 86,
"symbol": "Rn",
"name": "Radon",
"atomicMass": 222,
"electronegativity": "",
"standardState": "gas",
"groupBlock": "noble gas",
},
{
"atomicNumber": 87,
"symbol": "Fr",
"name": "Francium",
"atomicMass": 223,
"electronegativity": 0.7,
"standardState": "solid",
"groupBlock": "alkali metal",
},
{
"atomicNumber": 88,
"symbol": "Ra",
"name": "Radium",
"atomicMass": 226,
"electronegativity": 0.9,
"standardState": "solid",
"groupBlock": "alkaline earth metal",
},
{
"atomicNumber": 89,
"symbol": "Ac",
"name": "Actinium",
"atomicMass": 227,
"electronegativity": 1.1,
"standardState": "solid",
"groupBlock": "actinoid",
},
{
"atomicNumber": 90,
"symbol": "Th",
"name": "Thorium",
"atomicMass": "232.03806(2)",
"electronegativity": 1.3,
"standardState": "solid",
"groupBlock": "actinoid",
},
{
"atomicNumber": 91,
"symbol": "Pa",
"name": "Protactinium",
"atomicMass": "231.03588(2)",
"electronegativity": 1.5,
"standardState": "solid",
"groupBlock": "actinoid",
},
{
"atomicNumber": 92,
"symbol": "U",
"name": "Uranium",
"atomicMass": "238.02891(3)",
"electronegativity": 1.38,
"standardState": "solid",
"groupBlock": "actinoid",
},
{
"atomicNumber": 93,
"symbol": "Np",
"name": "Neptunium",
"atomicMass": 237,
"electronegativity": 1.36,
"standardState": "solid",
"groupBlock": "actinoid",
},
{
"atomicNumber": 94,
"symbol": "Pu",
"name": "Plutonium",
"atomicMass": 244,
"electronegativity": 1.28,
"standardState": "solid",
"groupBlock": "actinoid",
},
{
"atomicNumber": 95,
"symbol": "Am",
"name": "Americium",
"atomicMass": 243,
"electronegativity": 1.3,
"standardState": "solid",
"groupBlock": "actinoid",
},
{
"atomicNumber": 96,
"symbol": "Cm",
"name": "Curium",
"atomicMass": 247,
"electronegativity": 1.3,
"standardState": "solid",
"groupBlock": "actinoid",
},
{
"atomicNumber": 97,
"symbol": "Bk",
"name": "Berkelium",
"atomicMass": 247,
"electronegativity": 1.3,
"standardState": "solid",
"groupBlock": "actinoid",
},
{
"atomicNumber": 98,
"symbol": "Cf",
"name": "Californium",
"atomicMass": 251,
"electronegativity": 1.3,
"standardState": "solid",
"groupBlock": "actinoid",
},
{
"atomicNumber": 99,
"symbol": "Es",
"name": "Einsteinium",
"atomicMass": 252,
"electronegativity": 1.3,
"standardState": "solid",
"groupBlock": "actinoid",
}
]